### ISSUE TITLE
Forms cannot be moved once inserted

### ISSUE THREAD

**Issue by david-volcanic** [volcanic-uk/Mayon-CMS-tools#8]
![image](https://user-images.githubusercontent.com/7555653/44799285-770e8e00-abab-11e8-9cb1-500687265382.png)

**Comment by mouhannad-sh** [comment]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/18495740/45212222-eb8daf00-b2c6-11e8-9f92-4e2050302628.gif)
